### ISSUE TITLE
Have protected builder functions

### ISSUE THREAD

**Issue by cornerman** [raquo/scala-dom-types#12]
Can we make builder functions like `attr` in [`AttrBuilder`](https://github.com/raquo/scala-dom-types/blob/master/shared/src/main/scala/com/raquo/domtypes/generic/builders/AttrBuilder.scala#L15) `protected`?

Then the consuming library can decide whether it exposes them by implementing the method protected or not. This has the advantage of being able to expose a different interface for user-defined attributes.

**Comment by raquo** [comment]
Yeah, makes sense. I've protected all builders' methods in https://github.com/raquo/scala-dom-types/commit/4a7b8ccd22e539aab0f6e7fc78c2ab72be8b827a

I think I'd like to leave `Tag.build` public for now. It doesn't quite seem to fit into the same category as other builder methods, and I'm also using it in [TagSyntax](https://github.com/raquo/scala-dom-builder/blob/master/shared/src/main/scala/com/raquo/dombuilder/generic/syntax/TagSyntax.scala) in Scala DOM Builder. Being forced to use inheritance there doesn't feel right...

**Comment by raquo** [comment]
I thought about it some more and managed to convince myself that `Tag` shouldn't even have a `build` method for the same reason that `Attr` doesn't have a `setAttribute` method. In my universe, those kinds of methods should belong to the `DomApi` package defined in Scala DOM Builder (which I will eventually extract into a `Scala DOM API` project).

I will rework Scala DOM Builder accordingly. Removed `Tag.build` method in 7ef248e7b098ff107d5e21d561fcf12eb66d0dde
