### ISSUE TITLE
Every event should be of type TypedTargetEvent

### ISSUE THREAD

**Issue by cornerman** [raquo/scala-dom-types#17]
Currently, only a handful of the event properties are defined as a `TypedTargetEvent`, some are plain `dom.Event`. For convenience, it would be good if we could assume this for every event, i.e., every event is at least a `TypedTargetEvent[dom.EventTarget]`.

**Comment by raquo** [comment]
But `dom.Event` from scala-js-dom already has `target` typed as `dom.EventTarget`, no need for `TypedTargetEvent[dom.EventTarget]`. Or did you mean something else?

**Comment by cornerman** [comment]
My use-case was that I wanted my EventPropBuilder to produce events of type `TypedTargetEvent[_ <: dom.EventTarget]`. But actually, I do not really need it anymore, so I can think we can close it again :)
