### ISSUE TITLE
Document basic usage

### ISSUE THREAD

**Issue by raquo** [raquo/scala-dom-types#19]
- Add ToC to readme
- Docs:
  - Shared code, generic vs jsdom, various def lists
  - Keys, nodes including reuse of those types in many libraries
  - Builders and canonical builders
  - Modifier type
  - mention sameRefTags somewhere
  - bundles, and example usage (reference SDB or laminar)

**Comment by fdietze** [comment]
For reference, here is the usage in Outwach:
https://github.com/OutWatch/outwatch/blob/master/src/main/scala/outwatch/dom/DomTypes.scala

**Comment by tflucke** [comment]
Link is broken, new link seems to be here:
[https://github.com/OutWatch/outwatch/blob/master/outwatch/src/main/scala/outwatch/definitions/DomTypes.scala](https://github.com/OutWatch/outwatch/blob/master/outwatch/src/main/scala/outwatch/definitions/DomTypes.scala)

That said, I am trying to use this library and this doesn't seem to help much.  Something like a basic, "Hello World" would be very useful.

**Comment by cornerman** [comment]
@tflucke scala-dom-types is more of a library that web-frameworks/libraries can build upon.

To my knowledge, there are two web-libraries using scala-dom-types: [outwatch](https://github.com/outwatch/outwatch) and [laminar](https://github.com/raquo/laminar). You can check out the readme of each of them to find out about the usage!

**Comment by raquo** [comment]
I've added a few paragraphs of explanation based on a practical Laminar example, that'll have to suffice for now. If anyone has more specific usage / integration questions, please create a new issue or ask in the Laminar [gitter room](https://gitter.im/Laminar_/Lobby), I'll close this old unspecific issue as I did write most of the stuff I wanted originally.
