### ISSUE TITLE
Modifier trait should not qualify as a SAM type

### ISSUE THREAD

**Issue by raquo** [raquo/scala-dom-types#27]
I made Modifier a separate trait for safety, to prevent users from passing any random function as a modifier. The idea is that end users should generally not be easily creating their own modifiers on the fly, but should mostly be using modifiers provided to them by the consuming library.

However, Scala 2.12 magic SAM syntax silently converts any lambda literal like `el => foo` into a Modifier because Modifier qualifies as a SAM type (rules are [here](http://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#sam-conversion)).

Specifically, this interferes with Laminar's syntax where I have an implicit conversion from `A => Modifier[A]` to `Modifier[A]`. With 2.12, that conversion is never triggered because Scala magicks `A => Modifier[A]` into `A => Unit` (I guess?) which magicks into Modifier[A].

---

There are a couple ways to solve this problem that I know of:

1) Modifier trait should not extend Function1, and should instead define its own abstract `def apply[X](element: El): Unit` method. SAM syntax is not applied due to the phantom type param on apply.

2) Add an meaningless abstract `protected[this] def foo` to Modifier. This will make SAM syntax inapplicable, and if I'm understanding Scala.js dead code elimination correctly, this bogus method will be eliminated from runtime.

I'm leaning towards Option 1 as it seems like less burden for implementers of Modifier, as well as more obvious that it will not affect runtime performance.

If I recall correctly there might be a compiler flag to disable SAM treatment, but I don't want to force end users to do that for their whole project. I just want to prevent this one trait from being magicked with.

I don't particularly like any of the options, so any ideas or pointers would be very welcome.

**Comment by cornerman** [comment]
How about using a `typeclass` for the implicit conversion of `A => Modifier[A]` to `Modifier[A]`? So you could have a typeclass `AsModifier[F]` with instances for `[A] Modifier[A]` and `[A] A => Modifier[A]`. Instead of accepting a Modifier and implicitly converting a function to Modifier, your method would then expect something that can be an `AsModifier`. This should not trigger a SAM conversion.

```scala
def func[T : AsModifier](modifier: T) = ???
```

**Comment by raquo** [comment]
Hm thanks, looks like a legit solution for this SAM problem in general. However, in this particular case I don't think it's a good fit because of probable performance impact on both compilation time (implicit search for every modifier, not just for thisNode => modifier) and runtime (don't think Scala.js will be able to optimize way the typeclass layer, so probably extra allocated objects and extra function calls). This matters because in a frontend app method calls which accept Modifier/AsModifier params would be extremely plentiful.

**Comment by raquo** [comment]
I also tried

```scala
  trait MetaModifier[-El] extends AsModifier[El] {

    override def apply(el: El): Unit = {
      makeModifier(el)(el)
    }

    def makeModifier(el: El): Modifier[El]
  }
```

hoping the SAM conversion magic for a `El => Modifier[El]` literal will choose this trait instead of coercing `Modifier[El]` to `Unit`, but no such luck, sigh.

**Comment by cornerman** [comment]
> However, in this particular case I don't think it's a good fit because of probable performance impact 

Performance might be an issue, but maybe not even that bad (would need to try it out and see the generated code). I just find typeclasses more reliable and clear than implicit conversion functions :)

Interestingly, when requiring a trait mixin like (`Modifier with AnyRef`), the SAM conversion does not apply. Not sure, whether this is viable solution:
```scala
scala> trait F { def f(a:Int):String }
defined trait F
scala> def f(x:F with AnyRef) = x.f(1)
f: (x: F)String
scala> f((i:Int) => "a")
<console>:13: error: type mismatch;
 found   : Int => String
 required: F
       f((i:Int) => "a")
```

**Comment by raquo** [comment]
Thanks, that's a workable solution too.

I didn't want to compromise the simplicity of Modifier type signatures even a bit, and eventually I realized that I can just make the apply method non-abstract:

```scala
trait Modifier[-El] {
  def apply(el: El): Unit = ()
}
```

Admittedly, now you can potentially forget to provide an implementation for your Modifier subclass. But since end users by and large will not be creating modifiers on the fly, this seems like the best tradeoff to make, and a reasonable price to pay to completely disable undesired SAM sugar.
