### ISSUE TITLE
Typed CSS

### ISSUE THREAD

**Issue by fdietze** [raquo/scala-dom-types#28]
I just stumbled about this: https://www.chromestatus.com/feature/5682491075592192

Typed CSS is something for the far future, but I wanted to write it down here.

**Comment by raquo** [comment]
Thanks, that's an interesting find. I wasn't aware of that development.

I'm gonna close this issue just because it'll be a few years until we can/should act on this in SDT, but it's good to have an issue related to this promising API for reference. CSS performance is an underappreciated problem.
