### ISSUE TITLE
Key renaming proposals

### ISSUE THREAD

**Issue by raquo** [raquo/scala-dom-types#51]
So I guess we'll be collecting a few attr renaming proposals here?

### `id` -> `idAttr`

Not sure if `id` reflected attribute is pulling its weight hogging up what could be the most common term name.

Variable shadowing is annoying in cases like `valueByIdMap.map { case (id, value) => ... }`.

Personally I'm not annoyed enough to change it yet. If anyone has a preference one way or another please let me know.

**Comment by cornerman** [comment]
I'll just throw in my opinion. I rarely use the `id` attribute in my code, therefore I am in favor of renaming the attribute to `idAttr`. For me, the usage pattern does not justify such a prominent name. Main factors are variable shadowing and surprises when moving code which use a variable named id.

**Comment by raquo** [comment]
### `name` -> `nameAttr`

Basically same logic as `id`. If one is renamed the other should probably be too.

**Comment by raquo** [comment]
### `param` -> `paramTag`

Very niche tag hogging a good name. Specifically, conflicts with URL DSL's query `param` name used in [Waypoint](github.com/raquo/Waypoint).

**Comment by fdietze** [comment]
I agree to all the renames!
