### ISSUE TITLE
Support HTML Dialog Element

### ISSUE THREAD

**Issue by Lasering** [raquo/scala-dom-types#85]
The HTMLDialogElement [has been added to scala-js-dom](https://github.com/scala-js/scala-js-dom/releases/tag/v2.3.0), it could also be added here.

**Comment by Lasering** [comment]
Would a PR help?

**Comment by raquo** [comment]
Yes but not right now. I'm in the middle of rewriting SDT in a completely
different format with source code generators. Once that is done "in a few
days", I'll be open to PRs onto the new branch.

**Comment by raquo** [comment]
@Lasering Could you please add `type Dialog = HTMLDialogElement` to `object html` in scalajs-dom, it seems that all other HTML element types have an alias there.

**Comment by raquo** [comment]
Sorry I'm just swamped with SDT / Laminar stuff myself.

**Comment by Lasering** [comment]
> @Lasering Could you please add `type Dialog = HTMLDialogElement` to `object html` in scalajs-dom, it seems that all other HTML element types have an alias there.

In progress

**Comment by Lasering** [comment]
The [PR](https://github.com/scala-js/scala-js-dom/pull/753) has been merged.
