### ISSUE TITLE
Add ff4s to list of UI libs that use scala-dom-types

### ISSUE THREAD

**Issue by buntec** [raquo/scala-dom-types#98]
Hi,

I'm working on yet another Scala.js frontend library that uses scala-dom-types for its DSL. I love this project and would be proud to have [ff4s](https://github.com/buntec/ff4s) listed in the readme.

Thank you for this wonderful library!

**Comment by raquo** [comment]
Awesome, great to hear! I've added it now.

**Comment by buntec** [comment]
I would love that!

**Comment by buntec** [comment]
@armanbilge that does the trick! Alas, I can't seem to get tailwind to work.

**Comment by yurique** [comment]
@armanbilge indeed! Thank you! It works now :)

**Comment by yurique** [comment]
@buntec the links to ff4s from the home page now lead to the working examples.

For tailwind - the main.css didn't have the tailwind directives, I fixed that as well.

**Comment by yurique** [comment]
@buntec if you start with a ff4s template from the homepage (scala2 and scala3) – you can edit it and then update the template (the `ff4s` / `ff4s_3` labels in the bottom right should be orange for you and clickable)

**Comment by yurique** [comment]
Just make sure to run it before updating, to make sure it works :)

**Comment by buntec** [comment]
@yurique Got it, thanks again!!!
