### ISSUE TITLE
How to add a new property to a img?

### ISSUE THREAD

**Issue by cyz1901** [raquo/scala-dom-types#99]
Hey @raquo i want to add crossOrigin(https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin) to img tag.

Do I just need to add this code in https://github.com/raquo/scala-dom-types/blob/04e66590f96216fe1e20036c4d9a32d59205526b/js/src/test/scala/com/thirdparty/defs/props/Props.scala#L713C2-L713C2 add code like

```lazy val crossOrigin: Prop[String, String] = stringProp("crossOrigin")```?

**Comment by raquo** [comment]
Hi, if you just want to add it to your laminar project, you can just say:

```
val crossOrigin: HtmlProp[String] = htmlProp("crossOrigin", StringAsIsCodec)
```

(`stringProp` is not accessible to users, IIRC)

If you want to add it to SDT, you need to create a record for it in `ReflectedHtmlAttrDefs.scala`, with property name "crossOrigin" and attr name "crossorigin". If you're not up for that, I'll do it eventually.

MDN link https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by cyz1901** [comment]
> Hi, if you just want to add it to your laminar project, you can just say:
> 
> ```
> val crossOrigin: HtmlProp[String] = htmlProp("crossOrigin", StringAsIsCodec)
> ```
> 
> (`stringProp` is not accessible to users, IIRC)
> 
> If you want to add it to SDT, you need to create a record for it in `ReflectedHtmlAttrDefs.scala`, with property name "crossOrigin" and attr name "crossorigin". If you're not up for that, I'll do it eventually.
> 
> MDN link https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
Hi @raquo 

like this? https://github.com/raquo/scala-dom-types/pull/100

If appropriate, could you help approve this pr?

Or what else do I need to add....

Actually, I hope to use the newly added attr in [Calico's](https://github.com/armanbilge/calico) DSL

Perhaps I should submit a PR to update Calico's dependencies after making changes in this repository
Finally, use the latest Calico version in my project?

**Comment by raquo** [comment]
Sure, please see my comments on that PR, it needs some small changes.

I am not sure what the Calico alternative to:

```scala
val crossOrigin: HtmlProp[String] = htmlProp("crossOrigin", StringAsIsCodec)
```

syntax is, it probably looks very similar, but it depends on their classes and method names.

**Comment by cyz1901** [comment]
> Sure, please see my comments on that PR, it needs some small changes.
> 
> I am not sure what the Calico alternative to:
> 
> ```scala
> val crossOrigin: HtmlProp[String] = htmlProp("crossOrigin", StringAsIsCodec)
> ```
> 
> syntax is, it probably looks very similar, but it depends on their classes and method names.

updated pr and need approve again

**Comment by raquo** [comment]
Ok, merged, thanks. I can make a release later this week, I think. If you need this sooner, you really should figure out how to add custom attributes in your Calico project, it should be a simple one-liner. Just so that you're not blocked by the SDT release process.

**Comment by cyz1901** [comment]
This is a good suggestion. Thank you for your help!
